### PR TITLE
Add LengthAwarePaginator to QueryBuilder

### LINKED ISSUE #531: whenAppended no longer working
I don't know if this is an QueryBuilder bug or Laravel has changed this call:

```
<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class PostResource extends JsonResource
{
    /**
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->getRouteKey(),
            'thumbnail' => $this->whenAppended('thumbnail'),
        ];
    }
}
```

```
class IndexController extends Controller
{
    public function __invoke()
    {
        $models = QueryBuilder::for(Post::class)
            ->allowedAppends([
                'thumbnail',
            ])
            ->jsonPaginate();

        return PostResource::collection($models);
    }
}
```
The appending fields are just not included in the response.

### PR DESCRIPTION
**Pull request by francoism90**
When using `->paginate()` or `->jsonPaginate()`, it seems it doesn't inject the appends when needed.
This should fix #531.

This does work, but please let me know if the code can improved. :)

### CODE REVIEW

**Review by dominikb — COMMENTED** [review]
Looks good to me. Does it make sense to add a test for this?

**Comment by francoism90** [comment]
@dominikb Thanks for your review. :)

It would be great if this could be merged, this is the only showstopper for upgrading to L8.

**Comment by francoism90** [comment]
@freekmurze Sorry, but will this ever be merged/fixed? It seems I'm not the only one having this issue and I'm only waiting for this fix or I need to downgrade the package to v2.

**Comment by freekmurze** [comment]
@francoism90 please have a little patience. We'll handle this we have some time. There are a lot of other issues and client projects that require our attention as well.

@francoism90 can you add a test that is fixed by this PR. This will ensure that we don't break this behaviour again.

**Comment by francoism90** [comment]
@freekmurze Sorry, I do understand client project have priority and I'm glad Spatie is maintaining so many open-source projects. :)

It doesn't seem to current `AppendTest` does tests only Model instances, no collections (this does work fine)/paginates. I'll try to rewrite the test, but it doesn't seem all that simple at first.

**Comment by freekmurze** [comment]
Thanks for your work on this! 👍

**Comment by francoism90** [comment]
@freekmurze Thanks for the merge! :+1:

**Pull request merged**
