### PR TITLE
Individual array delimiter for a single filter #450

### PR DESCRIPTION
**Pull request by btxtiger**
I was not able to get the tests running locally. Seems some database connection is required in setup.

### CODE REVIEW

**Comment by dominikb** [comment]
> I was not able to get the tests running locally. Seems some database connection is required in setup.

It uses a MySQL connection for some tests. Take a look at the parameters specified in `phpunit.xml.dist`.
I usually use a Docker container for my database:
```
docker run --name mysql -e MYSQL_ALLOW_EMPTY_PASSWORD=true -d -p 3306:3306 --rm  mysql:5.7
docker exec mysql mysql -u root -e 'create database laravel_query_builder;'
```

**Comment by btxtiger** [comment]
Tests passed now, except these:
```
There were 2 incomplete tests:

1) Spatie\QueryBuilder\Tests\QueryBuilderTest::it_can_get_a_query_from_a_relationship
This test proves that there's something wrong with Eloquent's getQuery()

/Users/john/repositories/laravel-query-builder/tests/QueryBuilderTest.php:175

2) Spatie\QueryBuilder\Tests\QueryBuilderTest::it_queries_the_correct_data_for_a_relationship_query
Currently broken due to Eloquent. See the above test.

/Users/john/repositories/laravel-query-builder/tests/QueryBuilderTest.php:198

OK, but incomplete, skipped, or risky tests!
Tests: 162, Assertions: 217, Incomplete: 2.
```

**Comment by btxtiger** [comment]
@AlexVanderbist Can you please estimate, when it can be merged or if there are open issues?

**Comment by btxtiger** [comment]
@AlexVanderbist There is a growing number of open pull requests. Is this project still being maintained?

**Comment by AlexVanderbist** [comment]
Hi @btxtiger, thanks for reminding me. The package itself has been pretty stable so I haven't been looking into the pull requests as much as I should've been. Also, tagging v3 prevented me from looking into the PRs too much. However, it's tagged now and I'm working through the open PRs.

**Comment by AlexVanderbist** [comment]
Thanks for the PR!

**Pull request merged**
