### PR TITLE
Fix for Warning

### LINKED ISSUE #754: when i use filters it give me a warning
Since symfony/http-foundation 5.1: Retrieving a non-string value from "Symfony\Component\HttpFoundation\InputBag::get()" is deprecated, and will throw a "Symfony\Component\HttpFoundation\Exception\BadRequestException" exception in Symfony 6.0, use "Symfony\Component\HttpFoundation\InputBag::all($key)" instead.

Since symfony/http-foundation 5.1: Passing a non-scalar value as 2nd argument to "Symfony\Component\HttpFoundation\InputBag::get()" is deprecated, pass a scalar or null instead.

here is my code

$result = QueryBuilder::for($query)
            ->allowedFilters([
                'status',
                AllowedFilter::custom('fields', new CaseFieldsFilter),
            ])
            ->defaultSort('-start_date')
            ->allowedSorts('start_date')
            ->paginate($this->pages);

### PR DESCRIPTION
**Pull request by shaunluedeke**
LOG.warning: str_contains(): Passing null to parameter

Fixes #754

### CODE REVIEW

**Comment by shaunluedeke** [comment]
This is a small bug that I noticed

**Comment by shaunluedeke** [comment]
LOG.warning: explode(): Passing null to parameter #2 ($string) of type string is deprecated in C:\Users\Shaun\PhpstormProjects\smart-bi\vendor\spatie\laravel-query-builder\src\QueryBuilderRequest.php on line 57

**Comment by freekmurze** [comment]
Thanks!

**Comment by shaunluedeke** [comment]
Np

**Pull request merged**
