### PR TITLE
[DOCS] Update Frontend implementation with a new one

### PR DESCRIPTION
**Pull request by cgarciagarcia**

### CODE REVIEW

**Comment by cgarciagarcia** [comment]
Sorry But I'm not sure wich branch should I target to my PR. If I'm wrong let me know to re-target.

**Comment by cgarciagarcia** [comment]
@AlexVanderbist  let me know if my library could be considered as part in your documentation

**Comment by freekmurze** [comment]
Thanks!

**Comment by cgarcia-lightit** [comment]
@freekmurze  Thanks for the approvals, Could you let me know who will release a new version? The change doesn't impact yet.

Screenshot 2024-08-05 at 11 49 50 AM

**Comment by freekmurze** [comment]
It should be visible now.

**Pull request merged**
