### PR TITLE
[3.0] fix: php 8.1 support

### PR DESCRIPTION
**Pull request by ankurk91**
backport https://github.com/spatie/laravel-query-builder/pull/702 
to v3.x

### CODE REVIEW

**Comment by freekmurze** [comment]
Please fix this by implementing the typehints instead of the attributes.

**Comment by ankurk91** [comment]
Version 3 need to support php v7.3 as well, the typehints would work on php 7.3?

**Comment by ankurk91** [comment]
type-hint worked on php 7.3.

I have replaced the attributes with types, please check.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
