### PR TITLE
Add pagination methods with appended query to next / previous URLs

### PR DESCRIPTION
**Pull request by d8vjork**
So when we use cursor pagination on our Laravel projects they doesn't maintain the filters, sorts, appends, etc.

This will return previous/next URLs on the cursorPagination with all of them appended so next URLs still returning relevant results.

### CODE REVIEW

**Comment by d8vjork** [comment]
Hope this makes sense for you guys, I can also provide some extra tests for make sure that this isn't broken in the future

**Comment by AlexVanderbist** [comment]
Hi, thanks for the PR! An extra test would be helpful to make sure the changes don't break anything unexpected and everything keeps working in the future. Do you think we need something similar for the regulation pagination too?

**Comment by d8vjork** [comment]
@AlexVanderbist most probably, will create tests & the rest of them asap

**Comment by d8vjork** [comment]
All right, although there are other tests failing (non related to this I think)he implementation is a little bit crappy

**Comment by d8vjork** [comment]
Well don't know how to test on PestPHP as I've never used it

I'll try to update this with v5's as soon as I've free time

**Comment by freekmurze** [comment]
@d8vjork https://testing-laravel.com for learning how to use Pest 🙂

**Comment by d8vjork** [comment]
@freekmurze So there's a way to progressively migrate tests from PHPUnit as Pest, I'll try with some of my projects. Thanks

**Pull request closed without merging**
