### PR TITLE
Allow nullable filter

### PR DESCRIPTION
**Pull request by enricodelazzari**

### CODE REVIEW

**Comment by enricodelazzari** [comment]
@AlexVanderbist Any news on this? Thanks

**Comment by AlexVanderbist** [comment]
Another great PR, thanks!

**Comment by patrickrobrecht** [comment]
@enricodelazzari @AlexVanderbist When upgrading from Laravel Query Builder 5.5.0 to 5.6.0, we noticed that this PR introduces a small change which is not fully backwards compatible as we expected according to Semantic Versioning. See PR #902 for details and a bugfix restoring backwards compatibility.

**Comment by patrickrobrecht** [comment]
As mentioned above, the change introduced by this PR is not fully backwards compatible. I've updated #902 to introduce a new method which provides the same behavior as `default(null)` did before merging this PR. Could you have a look on that.

**Pull request merged**
