### PR TITLE
Add search capabilities

### PR DESCRIPTION
**Pull request by axelitus**
Enhancement implementation discussed in #172

It allows the use of search[modifier]=term querystring parameters.

Full search support includes the following variants:
```
url?search=term
url?search:begins=term
url?search:ends=term
url?search:exact=term
url?search[field]=term
url?search:begins[field]=term
url?search:ends[field]=term
url?search:exact[field]=term
url?search[field1,field2]=term
url?search:begins[field1,field2]=term
url?search:ends[field1,field2]=term
url?search:exact[field1,field2]=term
url?search:split=term%20with%20spaces
url?search:split[field]=term%20with%20spaces
url?search:split[field1,field2]=term%20with%20spaces
url?search:split:begins=term%20with%20spaces
url?search:split:begins[field]=term%20with%20spaces
url?search:split:begins[field1,field2]=term%20with%20spaces
url?search:split:ends=term%20with%20spaces
url?search:split:ends[field]=term%20with%20spaces
url?search:split:ends[field1,field2]=term%20with%20spacesurl?search=term
```

## Usage

```php
// The search driver to use is automatically resolved depending on the querystring key syntax.

// Single field
QueryBuilder::for(Model::class)
    ->allowedSearches('field');

// Multiple fields
QueryBuilder::for(Model::class)
    ->allowedSearches(['field1', 'field2']);

// Force the search driver for specific fields (otherwise it will be dynamically resolved based on syntax)

// Set exact driver for field regardless of querystring syntax
QueryBuilder::for(Model::class)
    ->allowedSearches([
        Search::exact('field')
    ]);
```

### CODE REVIEW

**Comment by viezel** [comment]
Nice idea

**Comment by rossity** [comment]
@AlexVanderbist do you guys have plans to merge/implement this in the next major release? Haven't seen discussion on it.

**Comment by AlexVanderbist** [comment]
Hi, I really like this search feature but after careful consideration with some of my colleagues we've decided not to merge it in this version of the package. 

The main reason is that this way of building a search query is a bit too opinionated and will take us too far from the core idea of this package. All other features are (loosely) based on JSON:API spec so we're gonna try to keep the base feature set of the package as close to this standard as possible.

However, I really think this search feature would be great as a custom filter or maybe even a separate package that makes use of the Query Builder package. If this can be reworked as a custom filter, I'll happily merge the PR :) 

Thank you for the PR!

**Comment by viezel** [comment]
@ axelitus Maybe as a trait?

**Comment by axelitus** [comment]
@viezel I like the idea of a custom filter or a plugin package that can be installed and "just works" better than just a trait.

@AlexVanderbist I'll try to work something out, but currently, I'm really swamped with work at the office and don't know how much time will I have to work on this, so this may take a while :(

**Comment by AlexVanderbist** [comment]
@axelitus I know what it's like, hence the delay on the PR. Either way, this PR serves as a really good example on how to implement and advanced search filter!

**Comment by axelitus** [comment]
@AlexVanderbist yeah I know... there are times that just fall down like a snowball... don't worry about the delay. Yeah, the PR will serve as a starting point to extract that functionality. And if anyone sees the conversation and wants to jump into this, it's certainly welcome!

**Comment by axelitus** [comment]
I've received an email in a related issue #172 asking about the status of this feature:
image

The comment has since disappeared but I still rebased the on top of spatie's master branch to include the latest commits if anyone wants to use the code in the [PR branch](https://github.com/axelitus/laravel-query-builder/tree/add-search-capabilities) for the time being until a proper package is made. (I don't recommend to use this though, as it's already been decided not to include this in the package but to manage this as a Custom filter and your code will surely break when spatie's package gets updated).

**Comment by charliegilmanuk** [comment]
> I've received an email in a related issue #172 asking about the status of this feature:
> image
> 
> The comment has since disappeared but I still rebased the branch on top of spatie's master branch to include their latest commits. If anyone wants to use the code in the [PR branch](https://github.com/axelitus/laravel-query-builder/tree/add-search-capabilities) for the time being until a proper package is made. (I don't recommend to use this though, as it's already been decided not to include this in the package but to manage this as a Custom filter and your code will surely break when spatie's package gets updated).

Sorry yep that was me, I replied and then realised it'd been referenced here.

Thank you so much for your hard work, I will be using it in a small production project, tested the version that was behind and it was working perfectly how I envisaged so I'm sure the rebase will be solid.  It's a real shame it was decided not to be included, considering to do a fuzzy search otherwise I would need to run a query string like:

`/users?&filter[first_name]=jef&filter[last_name]=jef&filter[tel_no]=jef&filter[email]=jef`

It would be nice to at least be offered the option, whether it adheres completely to the spec or not, after all it would be completely optional. this branch query would be as simple as:

`/users?search=jef`

**Comment by serhatculhalik** [comment]
What is the alternative or long way to make search through query?

**Comment by VSG24** [comment]
> What is the alternative or long way of making a search through query?

You can easily achieve it using a custom filter:

```
class FilterMultipleFields implements Filter
{
    public function __invoke(Builder $query, $value, string $property): Builder
    {
        $fields = explode(',', $property);

        foreach ($fields as $field) {
            $query = $query->orWhere($field, '=', $value);
        }

        return $query;
    }
}
```

Use it like:

```
$builder = QueryBuilder::for(User::class)
      ->orderBy('id', 'desc')
       ->allowedIncludes('roles')
       ->allowedFilters(Filter::custom('q', FilterMultipleFields::class, 'first_name,last_name'));
```

Pass a comma separated list of properties you want to filter.

**Comment by kinnngg** [comment]
> > What is the alternative or long way of making a search through query?
> 
> You can easily achieve it using a custom filter:
> 
> ```
> class FilterMultipleFields implements Filter
> {
>     public function __invoke(Builder $query, $value, string $property): Builder
>     {
>         $fields = explode(',', $property);
> 
>         foreach ($fields as $field) {
>             $query = $query->orWhere($field, '=', $value);
>         }
> 
>         return $query;
>     }
> }
> ```
> 
> Use it like:
> 
> ```
> $builder = QueryBuilder::for(User::class)
>       ->orderBy('id', 'desc')
>        ->allowedIncludes('roles')
>        ->allowedFilters(Filter::custom('q', FilterMultipleFields::class, 'first_name,last_name'));
> ```
> 
> Pass a comma separated list of properties you want to filter.

Why this thing is group all or Where clause.
Even it is group all AND where clauses I am doing outside of the custom filter.

```php
$questions = QueryBuilder::for(Question::class)
            ->select($builderOptions)
            ->defaultSort('-created_at')
            ->allowedSorts($builderOptions)
            ->allowedFields($builderOptions)
            ->where('is_practice_question', true)
            ->allowedFilters($filterOptions)
            ->paginate(request()->get('per_page')
            && request()->get('per_page') <= 50
                ? (int)request()->get('per_page') : 10)
            ->appends(request()->query());
```

Its good that it will group all the where clauses of filter but idk why it is also keeping `and is_practice_question = 1` inside of that grouping. Can anyone help plz.

**Comment by kinnngg** [comment]
> > > What is the alternative or long way of making a search through query?
> > 
> > 
> > You can easily achieve it using a custom filter:
> > ```
> > class FilterMultipleFields implements Filter
> > {
> >     public function __invoke(Builder $query, $value, string $property): Builder
> >     {
> >         $fields = explode(',', $property);
> > 
> >         foreach ($fields as $field) {
> >             $query = $query->orWhere($field, '=', $value);
> >         }
> > 
> >         return $query;
> >     }
> > }
> > ```
> > 
> > 
> > Use it like:
> > ```
> > $builder = QueryBuilder::for(User::class)
> >       ->orderBy('id', 'desc')
> >        ->allowedIncludes('roles')
> >        ->allowedFilters(Filter::custom('q', FilterMultipleFields::class, 'first_name,last_name'));
> > ```
> > 
> > 
> > Pass a comma separated list of properties you want to filter.
> 
> Why this thing is group all orWhere clause with other where outside of filter.
> Even it is group all AND where clauses I am doing outside of the custom filter.
> 
> ```
> $questions = QueryBuilder::for(Question::class)
>             ->select($builderOptions)
>             ->defaultSort('-created_at')
>             ->allowedSorts($builderOptions)
>             ->allowedFields($builderOptions)
>             ->where('is_practice_question', true)
>             ->allowedFilters($filterOptions)
>             ->paginate(request()->get('per_page')
>             && request()->get('per_page') <= 50
>                 ? (int)request()->get('per_page') : 10)
>             ->appends(request()->query());
> ```
> 
> Its good that it will group all the where clauses of filter but idk why it is also keeping `and is_practice_question = 1` inside of that grouping. Can anyone help plz.

Nvm, I got it fixed by changing the CustomFilter function a bit. 
Seems like orWhere is very tricky in Laravel. Better to wrap them in a group if we have more other where clauses.

Posting if anyone finds it helpful.
```php
class FilterMultipleFields implements Filter
{
    public function __invoke(Builder $query, $value, string $property): Builder
    {
        $fields = explode(',', $property);


        $query->where(function($query) use ($fields, $value) {
            foreach ($fields as $field) {
                $query->orWhere($field, 'LIKE', "%".$value."%");
            }
        });

        return $query;
    }
}
```

**Comment by rigibore-charlie** [comment]
Had been usng axelitus' fork in a Laravel 5.8 project but unfortunately when I updated to Laravel 7 it broke as it was based on an older version.  So I updated package to latest and spent a bit of time doing it properly with the filter and added a feature.

I took the above and made it work for searching the relationships as well:

```php
<?php

namespace App\Http\Filters;

use Spatie\QueryBuilder\Filters\Filter;
use Illuminate\Database\Eloquent\Builder;

class SearchFields implements Filter
{
    public function __invoke(Builder $query, $value, string $fields): Builder
    {
        if (!is_array($fields)) $fields = explode(',', $fields);

        $query->where(function($query) use ($fields, $value) {
            foreach ($fields as $field) {
                // Process nested relationship searches differently
                if (stripos($field, '.')) {
                    $els = explode('.', $field);
                    $relation = $els[0];
                    $col = $els[1];

                    $query->orWhereHas($relation, function($query) use ($value, $col) {
                        $query->where($col, 'LIKE', "%$value%");
                    });
                } else {
                    $query->orWhere($field, 'LIKE', "%$value%");
                }
            }
        });

        return $query;
    }
}
```

Notice the dots in the search fields:
```php
->allowedFilters(AllowedFilter::custom('search', new SearchFields, 'name,creator.name,country.name'))
```

**Comment by thewebartisan7** [comment]
I have slightly changed the last SearchFields filter by using similar way of lowering value and column name.
Also I see that is not required to return the query builder as you do.

Here is:


```

public function __invoke(Builder $query, $value, string $fields)
    {
        if (!is_array($fields)) $fields = explode(',', $fields);

        $value = mb_strtolower($value, 'UTF8');

        $query->where(function($query) use ($fields, $value) {
            foreach ($fields as $field) {
                // Process nested relationship searches differently
                if (stripos($field, '.')) {
                    $field = explode('.', $field);
                    $relation = $field[0];
                    $field = $field[1];
                    $sql = "LOWER({$field}) LIKE ?";

                    $query->orWhereHas($relation, function($query) use ($value, $sql) {
                        $query->orWhereRaw($sql, ["%{$value}%"]);
                    });

                } else {
                    $sql = "LOWER({$field}) LIKE ?";
                    $query->orWhereRaw($sql, ["%{$value}%"]);
                }
            }
        });
    }

```

The query become:

```
select * from `users` where (LOWER(name) LIKE '%value%' or LOWER(email) LIKE '%value%') order by `id` desc limit 15 offset 0
```

**Comment by thewebartisan7** [comment]
I notice an issue if param are passed with comma, then $value is an array.

So here is updated version that will search by all values of $value when array:


```
    public function __invoke(Builder $query, $value, string $property)
    {
        if ($this->addRelationConstraint) {
            if ($this->isRelationProperty($query, $property)) {
                $this->withRelationConstraint($query, $value, $property);

                return;
            }
        }

        $wrappedProperty = $query->getQuery()->getGrammar()->wrap($property);

        $sql = "LOWER({$wrappedProperty}) LIKE ?";

        if (is_array($value)) {
            if (count(array_filter($value)) === 0) {
                return $query;
            }

            $query->where(function (Builder $query) use ($value, $sql) {
                foreach (array_filter($value) as $partialValue) {
                    $partialValue = mb_strtolower($partialValue, 'UTF8');

                    $query->orWhereRaw($sql, ["%{$partialValue}%"]);
                }
            });

            return;
        }

        $value = mb_strtolower($value, 'UTF8');

        $query->whereRaw($sql, ["%{$value}%"]);
    }
```


```
select * from `users` where (LOWER(name) LIKE '%super admin%' or LOWER(name) LIKE '%admin%' or LOWER(email) LIKE '%super admin%' or LOWER(email) LIKE '%admin%' or exists (select * from `roles` inner join `user_has_roles` on `roles`.`id` = `user_has_roles`.`role_id` where `users`.`id` = `user_has_roles`.`user_id` and (LOWER(name) LIKE '%super admin%' or LOWER(name) LIKE '%admin%'))) order by `id` desc limit 15 offset 0
```

**Comment by kingpabel** [comment]
I notice issues for unexpected spaces with empty string, that's why I did more slightly modification to use a few array method.

```
public function __invoke(Builder $query, $value, string $fields)
    {
        is_array($fields) ?: $fields = explode(',', $fields);
        $fields = array_filter(array_map('trim', $fields));

        is_array($value) ?: $value = [$value];
        $value = array_filter(array_map(fn ($val) => mb_strtolower(trim($val), 'UTF8'), $value));

        if (empty($value)) {
            return;
        }

        $query->where(function (Builder $query) use ($fields, $value) {
            foreach ($fields as $field) {
                // Process nested relationship searches differently
                if (stripos($field, '.')) {
                    [$relation, $field] = explode('.', $field);
                    $sql = "LOWER({$field}) LIKE ?";

                    $query->orWhereHas($relation, function ($query) use ($value, $sql) {
                        $query->where(function (Builder $query) use ($value, $sql) {
                            foreach ($value as $partialValue) {
                                $query->orWhereRaw($sql, ["%{$partialValue}%"]);
                            }
                        });
                    });
                } else {
                    $sql = "LOWER({$field}) LIKE ?";
                    foreach ($value as $partialValue) {
                        $query->orWhereRaw($sql, ["%{$partialValue}%"]);
                    }
                }
            }
        });
    }
```

Sql will generate as like @thewebartisan7 mentioned

**Pull request closed without merging**
